### ISSUE TITLE
라이센스문의

### ISSUE THREAD

**Issue by merovingiaan** [krikit/annie#19]
안녕하세요.

한국어 오픈소스 NER 을 찾다가 오게되었는데요.

혹시 라이센스 알수있을까요... 

라이센스가 가능하다면 개조해서 업무에 사용가능할지 테스트 해보고 싶은데요.

감사합니다.

**Comment by krikit** [comment]
readme에 표시했습니다만, 라이센스 권리 행사를 할 계획이 없으니 마음껏 사용하시면 됩니다.
