### ISSUE TITLE
개체명 코퍼스 공유

### ISSUE THREAD

**Issue by j-min** [krikit/annie#20]
안녕하세요. annie를 사용해보고 싶은데 아쉽게도 형식에 맞는 마땅한 코퍼스를 찾지 못해서 문의드립니다.

혹시 dev.json/train.json 에 들어갈 수 있는 국립국어원 개체명 코퍼스 혹은 기타 개체명 코퍼스를 공유해주실 수 있으실까요?

감사합니다.

**Comment by krikit** [comment]
README 파일에 코퍼스의 라이센스 관련 내용을 추가했으니 한번 보시기 바랍니다.
제가 함부로 코퍼스를 공유하는 것은 아무래도 해당 코퍼스의 라이센스 정책에 맞는 지 잘 모르니까요. ^^;
첨부한 "사용허가협약" 파일에 서명하여 ETRI의 담당자에게 보내면 아마 CD를 보내줄 걸로 생각합니다.

참고로, CD안에 있는 개체명 코퍼스는 아래와 같은 원시 코퍼스로 되어 있습니다.

```
<우리금융그룹:OG>은 <19일:DT> <지난주부터:DT> <네덜란드:LC> 프로축구 <에인트호벤:OG>의 미드필더 <박지성:PS>과 <미국:LC> 프로야구 <텍사스 레인저스:OG>의 투수 <박찬호:PS>를 모델로 기용, 공중파 텔레비전을 통해 광고를 재개했다고 밝혔다 .
```

이를 자동으로 형태소분석을 수행하여 학습 가능한 JSON 포맷으로 변환하는 작업을 추가로 해주셔야 할 겁니다.
대회 참가자들에게 공개한 JSON 포맷의 학습 및 평가 코퍼스는 국립국어원이나 대회 담당자에게 문의해 보시는 것이 좋을 듯 합니다.

**Comment by j-min** [comment]
네 국립국어원과 ETRI에 문의해 보겠습니다. 친절한 답변 주셔서 감사합니다!
