### ISSUE TITLE
dev.json파일을 받을 수 있을까요??

### ISSUE THREAD

**Issue by stray-leone** [krikit/annie#21]
안녕하세요 :)

공개하신 개체명 인식기를 실행해보고 싶은데요,
실행 예에서 지정한 dev.json 파일을 못 찾아서 죄송하게도 이렇게 issue를 올리게 되었습니다.
혹시 포멧이라도 알려주시면 한번 실행해 보고 싶은데요....
받을 수 있을까요?? 아니면... 제가 잘 못 찾은 걸까요;;;

**Comment by krikit** [comment]
간단하게 말씀드리면 제가 데이터를 배포하는 것은 데이터의 라이센스 정책을 알 수 없어 힘들다는 겁니다.
보다 자세한 내용은 README.md 파일과 #20 이슈를 참고하시기 바랍니다.

**Comment by stray-leone** [comment]
아 그렇군요 .... 답변 주셔서 감사합니다 :)
