### ISSUE TITLE
질문있습니다.

### ISSUE THREAD

**Issue by ChoiGH** [krikit/annie#22]
안녕하세요. 귀하의 annie의 배포를 감사드립니다.
질문이 있는데요, json 형식을 어떻게 만들어야 하나요?
json 형식의 예시를 알려주셨으면 좋겠습니다.

좋은 하루 되세요.

**Comment by krikit** [comment]
아래 국립국어원 언어정보나눔터의 국어정보경진대회 2016년도에 가셔서,
https://ithub.korean.go.kr/user/contest/contestIntroLastView.do
심사방법 탭의 붙임자료: 2016년 국어 정보 처리 시스템 경진 대회 심사환경 안내.hwp 파일을 보시면,
중간에 결과파일의 JSON 형식이 있습니다.

**Comment by ChoiGH** [comment]
답변 감사합니다.
위 형식은 출력 형식이던데 입력 형식도 똑같나요? 이해가 잘 안되네요.

**Comment by ChoiGH** [comment]
{
        "sentence" : "맥스웰 방정식(Maxwell方程式, )은 전기와 자기의 발생, 전기장과 자기장, 전하 밀도와 전류 밀도의 형성을 나타내는 4개의 편미분 방정식이다.",
}

이렇게 하는게 맞나요

**Comment by krikit** [comment]
네. 본 프로그램은 대회에 참가하기 위해 만든 것이라 일반적인 문장을 넣으면 안됩니다.

위에 말씀드린 출력 결과 JSON 포맷과 동일하게 아이디(id), 원문(text), 어절(word), 형태소(morph)가 필요합니다.
그러면 개체명(NE) 필드를 추가하여 출력해 줍니다.

만약 임의의 문장을 이용해 돌려보고 싶으시다면, 세종 코퍼스 태그셋에 맞는 형태소 분석기를 돌려 그 결과를 이용하여 JSON 포맷을 생성하여 입력으로 넣으셔야 합니다.

**Comment by sukwoong** [comment]
안녕하세요 저도 위의 질문과 같은 맥락인데 
해당 json에서 
"morp" : ["id":0, "lemma":"맥스웰", "type": "NNG', "position": 20}, ....]
이 있는데 여기서 position 값은 어떤걸 의미하며 어떻게 구할 수 있는 값인지요?

감사합니다.
