### ISSUE TITLE
어떻게 사용하나요?

### ISSUE THREAD

**Issue by softmarshmallow** [krikit/annie#23]
한국어 유일의 NER 모듈이라 할수있습니다.
그에비해 documentation이 부족하고, 어떻게 자신의 프로젝트에 적용시킬수있는지에 대한 내용이 없습니다.

**Comment by krikit** [comment]
이 프로젝트는 2년 전에 한글 및 한국어 정보처리 학술대회와 함께 열린 국립국어원의 국어정보처리 시스템 경진대회의 지정분야에 제출하기 위해 진행했던 것입니다.
연구 결과물이나 프로토타입에 가까운 것으로 실제 서비스에 적용하기에는 좀 무리가 있습니다. 발표자료에 나타난 개념적인 부분만 참고하셔서 실무에 맞게 새로 작성하시길 권고 드립니다.
완성된 훌륭한 시스템에 유지보수도 되면 좋겠지만, 제가 그렇게 시간을 들일 여유가 없어 죄송하게 생각합니다.
